GET http://localhost:9000/user

######
POST http://localhost:9000/signup
Content-Type: application/json

{
    "username": "malini",
    "email": "malini@mail.com",
    "phone_number": "858632483",
    "password": "welcome123",
    "confirm_password": "Welcome123"
}

####
POST http://localhost:9000/signin
Content-Type: application/json

{
    "email": "malini@mail.com",
    "password": "welcome123"
}
