 GET http://localhost:9000

######
POST http://localhost:9000/signup
Content-Type: application/json

{
    "name": "rajkumar",
    "email": "rajkumar@mail.com",
    "password": "gokul1234"
}

####
POST http://localhost:9000/login
Content-Type: application/json

{
    "emal": "ranjani@mail.com",
    "password": "suraya123"
}
